spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
    password: come on
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
  sql:
    init:
      mode: always

spreadsheets:
  set-validation: true
  port: 8888
  application:
    name: Google Sheet API
  owner: dilshodlatipov748@gmail.com
  file:
    path:
      tokens: tokens
  spreadsheetId: 12BLCE2P3WZHsY5XpbsxFhPxZD4J2ZAPRKnRJhVfJod8
  sheetName: students
  sheetId: 0
  range:
    begin:
      col: A
      row: 2
    end:
      col: G
server:
  port: 80